### ISSUE TITLE
telnet escaping in write function?

### ISSUE THREAD

**Issue by kai-morich** [ClusterM/usb-serial-telnet-server#1]
I used org.apache.commons.net.telnet in my SerialWifiTerminal app. Interesting to see, that this can also be done without dependency in a single file, but don't you also have to take care of 0xFF escaping in write() https://github.com/ClusterM/usb-serial-telnet-server/blob/c7a877f0eb66b7a78d157efed51077ad4547d027/app/src/main/java/com/clusterrr/usbserialtelnetserver/TcpClientThread.java#L131?

**Comment by ClusterM** [comment]
Thank you, i'll fix it soon.

**Comment by ClusterM** [comment]
Done. Check release v1.3: https://github.com/ClusterM/usb-serial-telnet-server/releases/tag/v1.3
Also, it will be uploaded to Google Play soon.

**Comment by ClusterM** [comment]
Any feedback?
