### ISSUE TITLE
USB serial device not found

### ISSUE THREAD

**Issue by brandonros** [ClusterM/usb-serial-telnet-server#2]
CDC device works when I use this app: https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal&hl=en_US&gl=US

**Comment by ClusterM** [comment]
I'm afraid that it depends on the library that i'm using :(

**Comment by brandonros** [comment]
Does this repo not support if the Android Linux kernel "grabs"/attaches the serial device as a USB-CDC device?

I'd like to work with you to workaround this because I already need to do this as a WebUSB workaround.

What work would it take to achieve the same functionality as https://github.com/kai-morich/SimpleUsbTerminal?

**Comment by brandonros** [comment]
My idea is to be able to have a user run this app on their device, and then through the web browser (Chrome for Android), open a WebSocket that will act as a proxy read/write for WebSocket.

Now that I type it outloud, telnet won't really work here for that use case. I'd probably need to add websockify.

**Comment by brandonros** [comment]
Both your repo and the SimpleUSBTerminal use the https://github.com/mik3y/usb-serial-for-android library which is supposed to have CDC support.

**Comment by brandonros** [comment]
I bet it was just as simple as my vendor ID + device ID missing from https://github.com/ClusterM/usb-serial-telnet-server/blob/master/app/src/main/res/xml/usb_device_filter.xml since they are non-standard
