### ISSUE TITLE
Add option to automatically start on USB connection

### ISSUE THREAD

**Issue by Dakkaron** [ClusterM/usb-serial-telnet-server#4]
I made a keyboard attachment for my phone (https://github.com/Dakkaron/Fairberry) and would like to be able to send commands to it (e.g. screen is on/off, screen rotation changed, ...).

The best way that I found so far, short of writing my own companion app, is to use this telnet server to adapt from USB serial to telnet. Then I use Llamalab's Automate app to trigger a bash script which then uses busybox telnet to connect to the USB serial telnet server.

The only issue with this setup is, that I have to restart the server every time I reconnect the keyboard. I already set the app as the default app for the keyboard, so it automatically opens when I connect the keyboard.

Would it be possible to have an option that then automatically starts the server and closes the activity, so that connecting the device just silently starts the server without user interaction?

Btw, great app, thanks for your work!

**Comment by ClusterM** [comment]
I'll try to do it but later.

**Comment by Dakkaron** [comment]
Nice, thanks!

**Comment by ClusterM** [comment]
Done. Please check it in the latest release.

**Comment by Dakkaron** [comment]
Nice! Thanks!

**Comment by edoaxyz** [comment]
In my case it says "Missing USB permissions" everytime I try to disconnect and reconnect the USB cable to the phone, even if I granted the permission at first time, so it seems to not save the granted permission. Do you have any suggestion on how to fix this?

**Comment by ClusterM** [comment]
> In my case it says "Missing USB permissions" everytime I try to disconnect and reconnect the USB cable to the phone, even if I granted the permission at first time, so it seems to not save the granted permission. Do you have any suggestion on how to fix this?

Which Android version are you using? Is is asking for permissions again?
