### ISSUE TITLE
Please support Arduino Due

### ISSUE THREAD

**Issue by phatchman** [ClusterM/usb-serial-telnet-server#5]
Arduino Due is not detected. Details for the Due are below:
VID: 9025
PID: 61
Driver Type: CDC

**Comment by ClusterM** [comment]
I'm using [usb-serial-for-android  library by mik3y](https://github.com/mik3y/usb-serial-for-android), you need to ask him about this device support :(

**Comment by ClusterM** [comment]
Done. Please check it in the latest release.
