### ISSUE TITLE
autostart and multiport

### ISSUE THREAD

**Issue by msillano** [ClusterM/usb-serial-telnet-server#6]
**context:**
This APP is a good workaround to solve a big problem: in `Android+Termux+node-red` it is not possible to use _serial devices_: see [here](https://www.reddit.com/r/termux/comments/12gq6lt/nodered_the_nodeserialport_does_not_work_on_termux/).

So I looked for APPs, like "USB serial port IOT gateway" from apkpure: this is an interesting application, with the possibility of using many COM ports and many MQTT servers. Above all, it has one big flaw: it doesn't work in BACKGROUND.

Then I found your application, I tested it on `Android 11 + Termux` and `node-red`: OK and simple to use. Good job.
Thanks: I'm using it in my projects ([see here](https://github.com/msillano/tuyaDAEMON/wiki/custom-device-'PM-detector':-case-study#2023-implementation-android)).

**request**
 - A IOT server is unattended, i.e. at bootstrap all must fire. This is simple using `MacroDroid`,  but your application requires the user action to select "START".  An option 'autostart' (a button in config) can be a simple solution (see also ISSUE#4)

- A top-box can have many USB ports. So the capability to handle more [COM specs- TELNET port] pair, user-defined, but automatically chosen by the program at runtime, it would be a much-appreciated improvement (as an alternative, enable multi-instances capability).

Best regards.

**Comment by ClusterM** [comment]
Added autostart. Multiport is not planned yet.
