### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [ClusterM/usb-serial-telnet-server#9]
I've checked your app if its build is reproducible (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/catmin/articles/named/iod-rbs-mirrors-clients?lang=en)), but while I was able to successfully generate the APK using `./gradlew assembleRelease`, it didn't match yours. According to the diff in the `AndroidManifest.xml`, your APK cannot have been built from the commit the tag points to:

```diff
-    A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=9
+    A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=8
```

Looks rather like some uncommitted change, as even the manifest at the current `HEAD` still has `versionCode: 8`.

Could you please push the commit you've built from, and let me know what commit hash it is? And ideally, with future releases build the APK from a clean tree at the commit the tag points to? Thanks in advance!

PS: some more hints on increasing chances for a reproducible build can be found with our [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) in the IzzyOnDroid wiki :wink:

**Comment by ClusterM** [comment]
Fixed, thank you.

**Comment by IzzySoft** [comment]
Thanks! But: fixed how? Which commit is it I'd need to build the app from so it would be identical? I see the versioning is fixed in the latest commit now. So I guess I shall wait for the next release then to retry? Just need to know :wink:

**Comment by IzzySoft** [comment]
@ClusterM Any ETA for said release?

**Comment by IzzySoft** [comment]
@ClusterM any word?

**Comment by ClusterM** [comment]
@IzzySoft Sorry for not so fast answer. Check it now. It's 100% the same code used to build release.

**Comment by IzzySoft** [comment]
Thanks Alexey! This time it's me who has to apologize for the delay (I've been on vacation for the last 3 weeks). Seeing there were some new releases, I gave the latest one (v1.7) a try – and congrats, you made it! Here comes your [welcome toot](https://floss.social/@IzzyOnDroid/113271960585130148)

![image](https://github.com/user-attachments/assets/66e58161-b496-4c76-be3e-c05a6fdbfafe)

and maybe you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [your app at IzzyOnDroid](https://apt.izzysoft.de/packages/com.clusterrr.usbserialtelnetserver) e.g. from the Readme?
